version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/etc/traefik/

  frontend:
    image: nginx
    labels:

      ################ Routers ################
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.xyz.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      # SSL
      - "traefik.http.routers.frontend.tls.options=tls@file"
      - "traefik.http.routers.frontend.tls.certresolver=production"
      
      ################ services ################
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

      ################ middlewares ################
      - "traefik.http.routers.frontend.middlewares=headerpolicy@file"
      
  backend:
    image: httpd
    labels:

      ################ Routers ################
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`frontend.xyz.org`) && PathPrefix(`/backend`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      # SSL
      - "traefik.http.routers.backend.tls.options=tls@file"
      - "traefik.http.routers.backend.tls.certresolver=production"
      
      ################ services ################
      - "traefik.http.services.backend.loadbalancer.server.port=80"

      ################ middlewares ################
      - "traefik.http.routers.backend.middlewares=headerpolicy@file, replacepath@file"

    deploy:
      mode: replicated
      replicas: 2

  


